#+title: Formatting Pattern TIIG updates
#+author: Nathan Stonewall
#+email: nathan.stonewall@gs1.se
#+date: <2023-11-27 Mon>
#+OPTIONS: H:1 num:nil \n author:Nathan Stonewall date:2023-09-15 d:(not "HORSE")
#+OPTIONS: toc:nil
#+OPTIONS: \n:t
#+MACRO: NEWLINE @@latex:\\@@ @@html:<br>@@
#+HTML_HEAD: <style type="text/css">body{ max-width:80%; margin: auto;} .custom-list { margin-bottom: 50px; }</style>
#+SETUPFILE: https://fniessen.github.io/org-html-themes/org/theme-readtheorg.setup

* *43 Formatting for Descriptions*
This section deals with the usage of attributes that are of data type ~Description~.

There are five types of ~Descriptions~:

(...)

- ~Formatted Descriptions~ that allow (one/multiple) value(s) per language. In addition, enable user to enhance the visual presentation of their information using rich text styling, such as ordered lists, hyperlinks, and formatted text.

(...)

** *43.3 Formatted Description, one value per language (multiple languages allowed)*
*** How do I use ~Formatted Description~ to state that an item has components? For example, a bag of various candy bars, each of which has different properties that must be expressed in a ~Description~ field.
 Use a BBCode list:
#+BEGIN_SRC
[list]
[*] Component 1: Description of Component 1
[*] Component 2: Description of Component 2
[*] Component 3: Description of Component 3
[/list]
#+END_SRC

*** How do I represent a new line?
 Use a BBCode line break:
#+BEGIN_SRC
Some text here. [br] This text begins a new line.
#+END_SRC

*** How do I represent a new paragraph?
 Use a BBCode double line break:
#+BEGIN_SRC
Some text here. [br][br] This text begins a new paragraph.
#+END_SRC

*** How do I format text?
 Use appropriate BBCode formatting tags (see "BBCode Syntax" at section *43.6.3*):
#+BEGIN_SRC
Some [b]bold text[/b] here.
[br] This text begins a new line.
Some [i]italicized text[/i] here.
A simple list here: [br] [list]
[*]First list item
[*]Second list item
[/list]
#+END_SRC

*** Should I use ~@sequenceNumber~?
In general, no. Use an appropriate BBCode list instead.



** *43.4 Formatted Description, multiple values per language (multiple languages allowed)*
The same parameters and recommendations apply as in the previous section *43.3*.

When using ~Formatted Description~, consider carefully whether it is necessary to send multiple values in one and the same language. If possible, use BBCode formatting capabilities to provide all information in one value. This will allow systems tasked with handling the information to do so more gracefully.

** *43.5 Description one value, one language*
/Note to GDSN: Consider deleting if no longer relevant?/


** *43.6 Formatting Pattern Examples*

*** *43.6.1 Formatted Descriptions using BBCode*

The Standard leverages /BBCode/ to enable styling of trade item information. BBCode offers a simple framework for text and document formatting that is similar to HTML.

BBCode offers a more extensive range of formatting tools than is presented in this document. To simplify implementation, this document recommends the use of only a subset of BBCode. In principle however, breadth of implementation may be agreed upon between trading partners according to their needs.


*** *43.6.2 The reason for the design*
BBCode is recommended as the means to send styled trade item information using data type ~Formatted Description~, principally for security reasons. Allowing raw HTML code in trade item information exposes systems to injection attacks, while BBCode carries no such risks. In addition, the BBCode implementation places responsibility for interpretation of styled trade item information on the data recipient, who can choose to what extent it wishes to allow styled trade item information from their data source.

As the examples that follow illustrate, ~Formatted Description~ data type leverages the ~@formattingPattern~ XML attribute. All styled trade item information should be stored in ~@formattingPattern~, while its corresponding unstyled (plain text) information should be stored in its parent XML element.

With respect to the content of ~Formatted Description~ attributes, it is good practice to provide the same information at attribute level (styled) as at element level (plain text). See examples *43.6.4* and *43.6.5*.

*** *43.6.3 BBCode syntax*

 *Text formatting*
| Operation  | BBCode tag      | Tag must be closed |
|------------+-----------------+--------------------|
| Bold       | [b]             | Yes                |
| Italic     | [i]             | Yes                |
| Underline  | [u]             | Yes                |
| Font-size  | [size={number}] | Yes                |
| Font-color | [color={color}] | Yes                |

 *Structural formatting*
| Operation        | BBCode tag | Tag must be closed |
|------------------+------------+--------------------|
| Header (level 1) | [h1]       | Yes                |
| Header (level 2) | [h2]       | Yes                |
| Line break       | [br]       | No                 |
| Align left       | [left]     | Yes                |
| Align right      | [right]    | Yes                |
| Align center     | [center]   | Yes                |
| Unordered list   | [list]     | Yes                |
| Numbered list    | [list=1]   | Yes                |
| List item        | [*]        | No                 |

 *Other formatting*
| Operation    | BBCode tag                  | Tag must be closed |
|--------------+-----------------------------+--------------------|
| Link         | [url]{url here}             | Yes                |
| Named link   | [url={url here}]{link name} | Yes                |
| Insert image | [img]{url}                  | Yes                |

{{{NEWLINE}}}
*** *43.6.4 Simple Example: String with formatted text elements*

Content:

This string contains a *bold* substring and a link to a [[https://www.mywebsite.com][website]].

XML representation:

#+BEGIN_SRC XML
<tradeItemMarketingMessage formattingPattern="This string contains a [b]bold[/b] substring and a link to a [url={www.mywebsite.com}]website[/url].">
This string contains a bold substring and a link to a website.</tradeItemMarketingMessage>
 #+END_SRC


*** *43.6.5 Complex Example: Styled ingredients list*

Content:


- *5 X Pickled Onion Flavour Baked Corn Snack. Ingredients:* Maize, Vegetable Oil, Pickled Onion Flavour, Acidity Regulator (Sodium Diacetate), *Lactose (from Milk)*, Onion Powder, Flavourings, Citric Acid, Acetic Acid, *Wheat Rusk, Hydrolysed Soya Protein (contains Wheat)*, Flavour Enhancers (Monosodium Glutamate, Disodium 5’ribonucleotide), Fructose, *Celery Seed Oil*, Mustard Seed Oil, Colours (Sulphite Ammonia Caramel), Salt, Potassium Chloride, *Wheat Flour*.

- *4 X Flamin’ Hot Flavour Baked Corn Snack. Ingredients:* Maize, Vegetable Oil, Flamin Hot Flavour, *Hydrolysed Soya Protein*, Fructose, Flavourings, *Lactose (from Milk)*, Glucose Syrup, Flavour Enhancers (Monosodium Glutamate, Disodium 5’ribonucleotide), Acidity Regulator (Sodium Diacetate), Citric Acid, Tartaric Acid, *Wheat Rusk*, Sugar, Malic Acid, *Celery Seed Oil, Mustard Seed Oil*, Colours (*Sulphite Ammonia Caramel (from Wheat)*, Paprika Extract, *Curcumin (from Wheat)*, Salt, Potassium Chloride, Wheat Flour.

XML representation:
#+BEGIN_SRC XML
<ingredientStatement formattingPattern="
[list]
[*]
[b]5 X Pickled Onion Flavour Baked Corn Snack. Ingredients:[/b] Maize, Vegetable Oil,
Pickled Onion Flavour, Acidity Regulator (Sodium Diacetate), [b]Lactose (from Milk)[/b],
Onion Powder, Flavourings, Citric Acid, Acetic Acid, [b]Wheat Rusk, Hydrolysed Soya Protein
(contains Wheat)[/b], Flavour Enhancers (Monosodium Glutamate, Disodium 5’ribonucleotide),
Fructose, [b]Celery Seed Oil[/b], Mustard Seed Oil, Colours (Sulphite Ammonia Caramel),
Salt, Potassium Chloride, [b]Wheat Flour[/b].
[*]
[b]4 X Flamin’ Hot Flavour Baked Corn Snack. Ingredients:[b] Maize, Vegetable Oil,
Flamin Hot Flavour, [b]Hydrolysed Soya Protein[/b], Fructose, Flavourings,
[b]Lactose (from Milk)[/b], Glucose Syrup, Flavour Enhancers (Monosodium Glutamate,
Disodium 5’ribonucleotide), Acidity Regulator (Sodium Diacetate), Citric Acid,
Tartaric Acid, [b]Wheat Rusk[/b], Sugar, Malic Acid, [b]Celery Seed Oil,
Mustard Seed Oil[/b], Colours ([b]Sulphite Ammonia Caramel (from Wheat)[/b],
Paprika Extract, [b]Curcumin (from Wheat)[/b], Salt, Potassium Chloride, Wheat Flour.
[/list]">
5 X Pickled Onion Flavour Baked Corn Snack. Ingredients: Maize, Vegetable Oil,
Pickled Onion Flavour, Acidity Regulator (Sodium Diacetate), Lactose (from Milk),
Onion Powder, Flavourings, Citric Acid, Acetic Acid, Wheat Rusk, Hydrolysed Soya Protein
(contains Wheat), Flavour Enhancers (Monosodium Glutamate, Disodium 5’ribonucleotide),
Fructose, Celery Seed Oil, Mustard Seed Oil, Colours (Sulphite Ammonia Caramel)},
Salt, Potassium Chloride, Wheat Flour. 4 X Flamin’ Hot Flavour Baked Corn Snack.
Ingredients: Maize, Vegetable Oil, Flamin Hot Flavour [Hydrolysed Soya Protein,
Fructose, Flavourings, Lactose (from Milk), Glucose Syrup, Flavour Enhancers
(Monosodium Glutamate, Disodium 5’ribonucleotide), Acidity Regulator (Sodium Diacetate),
Citric Acid, Tartaric Acid, Wheat Rusk, Sugar, Malic Acid, Celery Seed Oil,
Mustard Seed Oil, Colours (Sulphite Ammonia Caramel (from Wheat), Paprika Extract,
Curcumin (from Wheat), Salt, Potassium Chloride, Wheat Flour.
</ingredientStatement>
 #+END_SRC
